from __future__ import annotations

import html
import json
from pathlib import Path


def write_report(
    summary: dict[str, object],
    output: Path,
    title: str,
    model_pattern: str,
) -> None:
    """Write a self-contained offline HTML report containing aggregates only."""

    payload = json.dumps(summary, ensure_ascii=False, separators=(",", ":")).replace(
        "</", "<\\/"
    )
    document = (
        _HTML.replace("__TITLE__", html.escape(title))
        .replace("__MODEL_PATTERN__", html.escape(model_pattern))
        .replace("__DATA__", payload)
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(document, encoding="utf-8")


_HTML = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>__TITLE__</title>
  <meta name="description" content="LM Studio prefill and decode throughput analysis generated locally from server logs.">
  <style>
    :root{color-scheme:light dark;--bg:light-dark(#f5f6fb,#0d0f17);--surface:light-dark(#fff,#151824);--surface2:light-dark(#edf0f8,#1c2030);--text:light-dark(#171a26,#f4f5fb);--muted:light-dark(#62697a,#a4aabd);--line:light-dark(#dfe3ed,#2b3042);--grid:light-dark(#e8ebf2,#252a3a);--a:light-dark(#5865e8,#8d98ff);--b:light-dark(#c04b68,#ff7898);--c:light-dark(#087b69,#55d6bd);--band:light-dark(#e7e9ff,#252b55);--shadow:light-dark(0 18px 50px rgba(36,42,67,.08),0 18px 50px rgba(0,0,0,.2))}
    *{box-sizing:border-box}html{font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}body{margin:0;min-width:320px}.page{width:min(1180px,calc(100% - 40px));margin:auto;padding:42px 0 56px}.mast{display:grid;grid-template-columns:1.35fr .65fr;gap:38px;align-items:end;margin-bottom:30px}.eyebrow{margin:0 0 10px;color:var(--a);font-size:.78rem;font-weight:750;letter-spacing:.13em;text-transform:uppercase}h1{margin:0;font-size:clamp(2rem,5vw,4.3rem);line-height:1;letter-spacing:-.055em}.lede{margin:14px 0 0;color:var(--muted);font-size:1.05rem;line-height:1.6}.meta{border-left:2px solid var(--a);padding-left:20px;color:var(--muted);line-height:1.65}.meta strong{color:var(--text)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:18px}.metric,.panel{min-width:0;border:1px solid var(--line);border-radius:18px;background:var(--surface);box-shadow:var(--shadow)}.metric{padding:22px}.metric-label{color:var(--muted);font-size:.84rem;font-weight:700}.metric-value{margin:8px 0 0;font-size:clamp(2rem,3vw,3rem);line-height:1;font-variant-numeric:tabular-nums}.metric-value small{color:var(--muted);font-size:.88rem}.metric-range{margin:10px 0 0;color:var(--muted);font-size:.8rem}.grid{display:grid;grid-template-columns:1.05fr .95fr;gap:18px}.panel{padding:22px}.wide{grid-column:1/-1}.panel-head{display:flex;justify-content:space-between;gap:20px;align-items:start;margin-bottom:8px}h2{margin:0;font-size:1.12rem}.copy{margin:6px 0 0;color:var(--muted);font-size:.84rem;line-height:1.5}.legend{color:var(--muted);font-size:.75rem;white-space:nowrap}.plots{display:grid;grid-template-columns:1fr 1fr;gap:24px}.subplot h3{margin:6px 0;color:var(--muted);font-size:.86rem}.chart{width:100%;min-height:330px}.chart svg{display:block;width:100%;height:auto;overflow:visible}.chart text{fill:var(--muted);font:12px inherit}.chart .value{fill:var(--text);font-weight:700}.chart .gridline{stroke:var(--grid)}.chart .axis{stroke:var(--line)}.chart .bar{fill:var(--a);opacity:.85}.chart .band{fill:var(--band)}.chart .line{fill:none;stroke:var(--b);stroke-width:2.5;stroke-linejoin:round;stroke-linecap:round}.chart .line.prefill{stroke:var(--a)}.chart .point{fill:var(--b);stroke:var(--surface);stroke-width:3}.chart .point.prefill{fill:var(--a)}.chart .whisker{stroke:var(--text);stroke-width:1.5}.tooltip{position:fixed;z-index:5;pointer-events:none;max-width:260px;padding:10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--surface2);box-shadow:var(--shadow);font-size:.78rem;line-height:1.45;opacity:0;transform:translate(-50%,-110%)}.tooltip.show{opacity:1}.tooltip strong{display:block}footer{display:flex;justify-content:space-between;gap:20px;margin-top:18px;color:var(--muted);font-size:.75rem;line-height:1.5}footer p{margin:0}code{color:var(--text)}
    @media(max-width:860px){.page{width:min(100% - 28px,760px);padding-top:28px}.mast,.grid,.plots{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(3,minmax(0,1fr))}}
    @media(max-width:620px){.metrics{grid-template-columns:1fr}.page{width:min(100% - 20px,480px)}.panel,.metric{padding:18px}.panel-head{display:block}.legend{margin-top:8px}footer{display:block}footer p+p{margin-top:8px}}
  </style>
</head>
<body>
  <main class="page">
    <header class="mast"><div><p class="eyebrow">LM Studio log analysis</p><h1 id="headline">Throughput report</h1><p class="lede">Prefill, decode, and active-context performance calculated locally from completed timing records.</p></div><div class="meta"><div><strong id="count">0</strong> paired requests</div><div id="dates">No dates</div><div>Model filter: <code>__MODEL_PATTERN__</code></div></div></header>
    <section class="metrics" aria-label="Typical throughput"><article class="metric"><div class="metric-label">Typical decode</div><div class="metric-value" id="decodeMetric">—</div><p class="metric-range" id="decodeRange"></p></article><article class="metric"><div class="metric-label">Substantial prefill · 512+ evaluated tokens</div><div class="metric-value" id="prefillMetric">—</div><p class="metric-range" id="prefillRange"></p></article><article class="metric"><div class="metric-label">Large prefill · 2k+ evaluated tokens</div><div class="metric-value" id="largeMetric">—</div><p class="metric-range" id="largeRange"></p></article></section>
    <section class="grid" aria-label="Throughput charts"><article class="panel"><div class="panel-head"><div><h2>Prefill by evaluated prompt size</h2><p class="copy">Shows batching efficiency for newly evaluated tokens.</p></div><div class="legend">Median · middle 50%</div></div><div class="chart" id="promptChart"></div></article><article class="panel"><div class="panel-head"><div><h2>Decode by day</h2><p class="copy">Makes session-to-session variability visible.</p></div><div class="legend">Median · middle 50%</div></div><div class="chart" id="dailyChart"></div></article><article class="panel wide"><div class="panel-head"><div><h2>Throughput by active context size</h2><p class="copy">Context at decode start is reconstructed as final slot tokens minus decoded tokens.</p></div><div class="legend">Median · middle 50%</div></div><div class="plots"><section class="subplot"><h3>Prefill</h3><div class="chart" id="contextPrefill"></div></section><section class="subplot"><h3>Decode</h3><div class="chart" id="contextDecode"></div></section></div></article></section>
    <footer><p>Generated locally. The report contains aggregates only—no prompts, responses, log lines, or source paths.</p><p>Median line · 25th–75th percentile band</p></footer>
  </main>
  <div class="tooltip" id="tip" role="tooltip" aria-hidden="true"></div>
  <script>
    const data=__DATA__,NS='http://www.w3.org/2000/svg',tip=document.getElementById('tip');
    const el=(n,a={},t='')=>{const x=document.createElementNS(NS,n);Object.entries(a).forEach(([k,v])=>x.setAttribute(k,v));if(t)x.textContent=t;return x};
    const fmt=v=>v==null?'—':Number(v).toFixed(1), summary=id=>data[id]||{};
    function metric(valueId,rangeId,s){document.getElementById(valueId).innerHTML=s.median==null?'—':`${fmt(s.median)} <small>tok/s</small>`;document.getElementById(rangeId).textContent=s.q1==null?'':`Middle 50%: ${fmt(s.q1)}–${fmt(s.q3)} tok/s · n=${s.count.toLocaleString()}`}
    document.getElementById('count').textContent=data.record_count.toLocaleString();document.getElementById('dates').textContent=data.date_min?`${data.date_min} to ${data.date_max}`:'No matching dates';document.getElementById('headline').textContent=data.decode.median==null?'No matching timing records':`Decode runs at about ${fmt(data.decode.median)} tokens per second.`;metric('decodeMetric','decodeRange',summary('decode'));metric('prefillMetric','prefillRange',summary('substantial_prefill'));metric('largeMetric','largeRange',summary('large_prefill'));
    function show(e,title,body){tip.innerHTML=`<strong>${title}</strong>${body}`;tip.style.left=`${Math.min(innerWidth-130,Math.max(130,e.clientX||innerWidth/2))}px`;tip.style.top=`${Math.max(90,e.clientY||120)}px`;tip.classList.add('show');tip.setAttribute('aria-hidden','false')}function hide(){tip.classList.remove('show');tip.setAttribute('aria-hidden','true')}
    function base(id,maxY,label){const host=document.getElementById(id);host.replaceChildren();const w=Math.max(320,Math.round(host.getBoundingClientRect().width)),h=350,m={top:28,right:14,bottom:58,left:w<430?48:58},iw=w-m.left-m.right,ih=h-m.top-m.bottom,svg=el('svg',{viewBox:`0 0 ${w} ${h}`,role:'img','aria-label':label}),g=el('g',{transform:`translate(${m.left} ${m.top})`}),y=v=>ih-v/maxY*ih;svg.append(el('title',{},label));svg.append(g);for(let i=0;i<=4;i++){const v=maxY*i/4,py=y(v);g.append(el('line',{class:'gridline',x1:0,x2:iw,y1:py,y2:py}));g.append(el('text',{x:-10,y:py+4,'text-anchor':'end'},v.toFixed(0)))}g.append(el('line',{class:'axis',x1:0,x2:iw,y1:ih,y2:ih}));svg.append(el('text',{x:15,y:m.top+ih/2,transform:`rotate(-90 15 ${m.top+ih/2})`,'text-anchor':'middle'},'Throughput (tok/s)'));host.append(svg);return{host,svg,g,w,iw,ih,m,y,compact:w<430}}
    function series(id,rows,keys,opt){const valid=rows.filter(d=>d.summary&&d.summary.median!=null),c=base(id,opt.maxY,opt.aria);if(!valid.length)return;const step=c.iw/(valid.length-1||1),pts=valid.map((d,i)=>({...d,x:i*step})),path=(key,reverse=false)=>{const a=reverse?[...pts].reverse():pts;return a.map((d,i)=>`${i?'L':'M'} ${d.x} ${c.y(d.summary[key])}`).join(' ')},band=`${path(keys.q3)} ${[...pts].reverse().map(d=>`L ${d.x} ${c.y(d.summary[keys.q1])}`).join(' ')} Z`;c.g.append(el('path',{class:'band',d:band}));c.g.append(el('path',{class:`line ${opt.prefill?'prefill':''}`,d:path(keys.med)}));pts.forEach((d,i)=>{const p=el('circle',{class:`point ${opt.prefill?'prefill':''}`,cx:d.x,cy:c.y(d.summary.median),r:5,tabindex:0,role:'graphics-symbol','aria-label':`${d.label||d.date}, median ${fmt(d.summary.median)} tokens per second`}),f=e=>show(e,d.label||d.date,`Median ${fmt(d.summary.median)} tok/s<br>Middle 50% ${fmt(d.summary.q1)}–${fmt(d.summary.q3)}<br>n=${d.summary.count.toLocaleString()}`);p.addEventListener('pointermove',f);p.addEventListener('focus',f);p.addEventListener('pointerleave',hide);p.addEventListener('blur',hide);c.g.append(p);c.g.append(el('text',{class:'value',x:d.x,y:c.y(d.summary.median)-11,'text-anchor':i===0?'start':i===pts.length-1?'end':'middle'},opt.value(d.summary.median)));if(!c.compact||i%2===0||i===pts.length-1)c.g.append(el('text',{x:d.x,y:c.ih+24,'text-anchor':i===0?'start':i===pts.length-1?'end':'middle'},opt.label(d))) });c.svg.append(el('text',{x:c.m.left+c.iw/2,y:344,'text-anchor':'middle'},opt.xTitle))}
    function bars(){const rows=data.prefill_by_prompt_tokens.filter(d=>d.summary.median!=null),c=base('promptChart',Math.max(10,...rows.map(d=>d.summary.q3))*1.12,'Prefill throughput by evaluated prompt tokens'),slot=c.iw/rows.length,bw=Math.min(58,slot*.56);rows.forEach((d,i)=>{const x=slot*i+slot/2,r=el('rect',{class:'bar',x:x-bw/2,y:c.y(d.summary.median),width:bw,height:c.ih-c.y(d.summary.median),rx:6,tabindex:0}),f=e=>show(e,`${d.label} evaluated tokens`,`Median ${fmt(d.summary.median)} tok/s<br>Middle 50% ${fmt(d.summary.q1)}–${fmt(d.summary.q3)}<br>n=${d.summary.count.toLocaleString()}`);r.addEventListener('pointermove',f);r.addEventListener('focus',f);r.addEventListener('pointerleave',hide);r.addEventListener('blur',hide);c.g.append(r);c.g.append(el('line',{class:'whisker',x1:x,x2:x,y1:c.y(d.summary.q1),y2:c.y(d.summary.q3)}));c.g.append(el('text',{class:'value',x,y:c.y(d.summary.q3)-8,'text-anchor':'middle'},d.summary.median.toFixed(0)));c.g.append(el('text',{x,y:c.ih+24,'text-anchor':'middle'},d.label))});c.svg.append(el('text',{x:c.m.left+c.iw/2,y:344,'text-anchor':'middle'},'Prompt tokens evaluated per request'))}
    function draw(){bars();series('dailyChart',data.daily_decode,{med:'median',q1:'q1',q3:'q3'},{maxY:Math.max(10,...data.daily_decode.map(d=>d.summary.q3||0))*1.1,aria:'Decode throughput by day',prefill:false,value:v=>v.toFixed(1),label:d=>d.date.slice(5),xTitle:'Completion date'});series('contextPrefill',data.prefill_by_context,{med:'median',q1:'q1',q3:'q3'},{maxY:Math.max(10,...data.prefill_by_context.map(d=>d.summary.q3||0))*1.1,aria:'Prefill throughput by active context',prefill:true,value:v=>v.toFixed(0),label:d=>d.label,xTitle:'Active context at decode start (tokens)'});series('contextDecode',data.decode_by_context,{med:'median',q1:'q1',q3:'q3'},{maxY:Math.max(10,...data.decode_by_context.map(d=>d.summary.q3||0))*1.1,aria:'Decode throughput by active context',prefill:false,value:v=>v.toFixed(1),label:d=>d.label,xTitle:'Active context at decode start (tokens)'})}
    let frame;new ResizeObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(draw)}).observe(document.querySelector('.grid'));draw();
  </script>
</body>
</html>'''
